/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2020-08-03 07:05:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frontpic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>商品管理システム</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t.img-slide{\r\n");
      out.write("\t\t\twidth:980px;\r\n");
      out.write("\t\t\tmargin:50px auto;\r\n");
      out.write("\t\t\tposition:relative;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img-slide img{\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t\t\tbox-shadow:5px 5px 5px #DDDDDD;\r\n");
      out.write("\t\t\tborder:1px solid #DDDDDD;\r\n");
      out.write("\t\t\tpading:8px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img1{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease 0s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img2{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -4s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img3{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -8s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img4{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -12s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@-webkit-keyframes slide{\r\n");
      out.write("\t\t\t0% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t\t20% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t\t25% {top:50px; left:480px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t45% {top:50px; left:480px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t50% {top:50px; left:200px; width:400px; z-index:1;}\r\n");
      out.write("\t\t\t70% {top:50px; left:200px; width:400px; z-index:1;}\r\n");
      out.write("\t\t\t75% {top:50px; left:0px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t95% {top:50px; left:0px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t100% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"img-slide\">\r\n");
      out.write("\r\n");
      out.write("\t\t<img src=\"id1.jpg\" alt=\"\" class=\"img1\" width=\"250\" height=\"250\">\r\n");
      out.write("\t\t<img src=\"id2.jpg\" alt=\"\" class=\"img2\" width=\"250\" height=\"250\">\r\n");
      out.write("\t\t<img src=\"id3.jpg\" alt=\"\" class=\"img3\" width=\"250\" height=\"250\">\r\n");
      out.write("\t\t<img src=\"id4.jpg\" alt=\"\" class=\"img4\" width=\"250\" height=\"250\">\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
