/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2020-08-19 10:11:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import manage.Category;
import manage.Wear;
import java.util.ArrayList;
import manage.Brand;
import manage.Catedetail;
import manage.Size;
import manage.Color;
import java.util.ArrayList;
import manage.Category;
import manage.Catemenu;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/view/footer.jsp", Long.valueOf(1595227668407L));
    _jspx_dependants.put("/view/header.jsp", Long.valueOf(1597823643926L));
    _jspx_dependants.put("/view/search.jsp", Long.valueOf(1597369805190L));
    _jspx_dependants.put("/view/bottom.jsp", Long.valueOf(1597823696199L));
    _jspx_dependants.put("/view/frontpic.jsp", Long.valueOf(1596513747574L));
    _jspx_dependants.put("/view/leftmenu.jsp", Long.valueOf(1597382967140L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("manage.Wear");
    _jspx_imports_classes.add("manage.Brand");
    _jspx_imports_classes.add("manage.Size");
    _jspx_imports_classes.add("manage.Color");
    _jspx_imports_classes.add("manage.Catedetail");
    _jspx_imports_classes.add("manage.Catemenu");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("manage.Category");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Category topname = (Category)request.getAttribute("topname");
ArrayList<Wear> wearList = (ArrayList<Wear>)request.getAttribute("wear_list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>商品管理システム</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t.box{\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.box-above{\r\n");
      out.write("\t\t\twidth:100%;\r\n");
      out.write("\t\t\theight:400px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.box-above2{\r\n");
      out.write("\t\t\twidth:100%;\r\n");
      out.write("\t\t\theight:50px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.box-left{\r\n");
      out.write("\t\t\twidth:25%;\r\n");
      out.write("\t\t\tbackground-color:#E5E5E5;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.box-right{\r\n");
      out.write("\t\t\twidth:75%;\r\n");
      out.write("\t\t\tbackground-color:#FFFFAA;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.box-bottom{\r\n");
      out.write("\t\t\twidth:100%;\r\n");
      out.write("\t\t\theight:200px;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t\tbackground-color:#A7CE02;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.float-left{\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.clearfix:after{\r\n");
      out.write("\t\t\tcontent:\"\";\r\n");
      out.write("\t\t\tdisplay:block;\r\n");
      out.write("\t\t\tclear:both;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"box\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t.box2{\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.left{\r\n");
      out.write("\t\twidth:25%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.right{\r\n");
      out.write("\t\twidth:75%;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t\tmargin:30px 0px 0px;\r\n");
      out.write("\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.bottom{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:10px;\r\n");
      out.write("\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t.float-left{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.clearfix:after{\r\n");
      out.write("\t\tcontent:\"\";\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\tclear:both;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"box2 clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"left float-left\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/GrandMenu\">\r\n");
      out.write("\t\t\t<img src=\"menutop.jpg\"  alt=\"ヘッダー\" width=\"250\" height=\"60\"></a></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"right float-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/view/logincustomer.jsp\">ログイン</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath() );
      out.write("/FreeSearch\">\r\n");
      out.write("\t\t\tフリーワード検索\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" value=\"\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"検索\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"bottom\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<hr style=\"height:5; background-color:#A7CE02\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"box-above\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>商品管理システム</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t.img-slide{\r\n");
      out.write("\t\t\twidth:980px;\r\n");
      out.write("\t\t\tmargin:50px auto;\r\n");
      out.write("\t\t\tposition:relative;\r\n");
      out.write("\t\t\ttext-align:center;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img-slide img{\r\n");
      out.write("\t\t\tposition:absolute;\r\n");
      out.write("\t\t\tbackground-color:#FFFFFF;\r\n");
      out.write("\t\t\tbox-shadow:5px 5px 5px #DDDDDD;\r\n");
      out.write("\t\t\tborder:1px solid #DDDDDD;\r\n");
      out.write("\t\t\tpading:8px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img1{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease 0s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img2{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -4s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img3{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -8s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.img4{\r\n");
      out.write("\t\t\t-webkit-animation:slide 16s ease -12s infinite normal\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@-webkit-keyframes slide{\r\n");
      out.write("\t\t\t0% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t\t20% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t\t25% {top:50px; left:480px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t45% {top:50px; left:480px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t50% {top:50px; left:200px; width:400px; z-index:1;}\r\n");
      out.write("\t\t\t70% {top:50px; left:200px; width:400px; z-index:1;}\r\n");
      out.write("\t\t\t75% {top:50px; left:0px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t95% {top:50px; left:0px; width:400px; z-index:3;}\r\n");
      out.write("\t\t\t100% {top:20px; left:200px; width:480px; z-index:4;}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"img-slide\">\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/Test\">\r\n");
      out.write("\t\t\t<img src=\"one.jpg\" alt=\"特集１\" class=\"img1\" width=\"250\" height=\"250\"></a>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/Test\">\r\n");
      out.write("\t\t\t<img src=\"ops.jpg\" alt=\"特集２\" class=\"img2\" width=\"250\" height=\"250\"></a>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/Test\">\r\n");
      out.write("\t\t\t<img src=\"summer.jpg\" alt=\"特集３\" class=\"img3\" width=\"250\" height=\"250\"></a>\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/Test\">\r\n");
      out.write("\t\t\t<img src=\"twin.jpg\" alt=\"特集４\" class=\"img4\" width=\"250\" height=\"250\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t<div class=\"box-above2\">");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<Brand> brandList = (ArrayList<Brand>)request.getAttribute("brand_list");
ArrayList<Catedetail> catedetailList = (ArrayList<Catedetail>)request.getAttribute("catedetail_list");
ArrayList<Size> sizeList = (ArrayList<Size>)request.getAttribute("size_list");
ArrayList<Color> colorList = (ArrayList<Color>)request.getAttribute("color_list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(request.getContextPath() );
      out.write("/WearSearch\">\r\n");
      out.write("\t<h3>全体検索</h3>\r\n");
      out.write("\r\n");
      out.write("\t<select name=\"brandid\">\r\n");
      out.write("\t\t<option style=\"color:#DCDCDC\" value=\"\">ブランド</option>\r\n");
      out.write("\t\t");

		for (int a = 0; a < brandList.size(); a++) {
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(brandList.get(a).getBrandid() );
      out.write('"');
      out.write('>');
      out.print(brandList.get(a).getBrandname() );
      out.write("</option>\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t<select name=\"catedetailid\">\r\n");
      out.write("\t\t<option style=\"color:#DCDCDC\" value=\"\">服分類</option>\r\n");
      out.write("\t\t");

		for (int b = 0; b < catedetailList.size(); b++) {
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(catedetailList.get(b).getCatedetailid() );
      out.write('"');
      out.write('>');
      out.print(catedetailList.get(b).getCatedetailname() );
      out.write("</option>\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t<select name=\"sizeid\">\r\n");
      out.write("\t\t<option style=\"color:#DCDCDC\" value=\"\">サイズ</option>\r\n");
      out.write("\t\t");

		for (int c = 0; c < sizeList.size(); c++) {
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(sizeList.get(c).getSizeid() );
      out.write('"');
      out.write('>');
      out.print(sizeList.get(c).getSizename() );
      out.write("</option>\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t<select name=\"colorid\">\r\n");
      out.write("\t\t<option style=\"color:#DCDCDC\" value=\"\">カラー</option>\r\n");
      out.write("\t\t");

		for (int d = 0; d < colorList.size(); d++) {
		
      out.write("\r\n");
      out.write("\t\t<option value=\"");
      out.print(colorList.get(d).getColorid() );
      out.write('"');
      out.write('>');
      out.print(colorList.get(d).getColorname() );
      out.write("</option>\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"submit\" value=\"検索\">\r\n");
      out.write("</form>");
      out.write("</div>\r\n");
      out.write("\t<div class=\"box clearfix\">\r\n");
      out.write("\t\t<div class=\"box-left float-left\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<Category> categoryList = (ArrayList<Category>)request.getAttribute("category_list");
ArrayList<Catemenu> catemenuList = (ArrayList<Catemenu>)request.getAttribute("catemenu_list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title></title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t<h4 style=\"text-align:center\">カテゴリ</h4>\r\n");
      out.write("\t<hr style=\"background-color:#A7CE02\"/>\r\n");
      out.write("\r\n");
      out.write("\t<table style=\"margin:0 auto\">\r\n");
      out.write("\r\n");
      out.write("\t");

	for (int i = 0; i < categoryList.size(); i++) {
	
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><a href=\"");
      out.print(request.getContextPath() );
      out.write("/Test?cmd=");
      out.print(categoryList.get(i).getCategoryid() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print( categoryList.get(i).getCategoryname() );
      out.write("</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");

	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t\t<div class=\"box-right float-left\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>");
      out.print(topname.getCategoryname() );
      out.write("</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th></th>\r\n");
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t");

		for (int i = 0; i < wearList.size(); i++) {
		
      out.write("\r\n");
      out.write("\t\t\t<th><a href=\"");
      out.print(request.getContextPath() );
      out.write("/WearDetail?id=");
      out.print(wearList.get(i).getId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(wearList.get(i).getName() );
      out.write("</a></th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<th><img src=\"");
      out.print(wearList.get(i).getImage() );
      out.write("\" alt=\"");
      out.print(wearList.get(i).getName() );
      out.write("\" width=\"150\" height=\"150\"></th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<th><a href=\"");
      out.print(request.getContextPath() );
      out.write("/InsertCart?id=");
      out.print(wearList.get(i).getId() );
      out.write("\">\r\n");
      out.write("\t\t\t\tカートに入れる</a></th>\r\n");
      out.write("\r\n");
      out.write("\t\t");

		}
		
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"box-bottom\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>商品管理システム</title>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t<h4 style=\"text-align:right\">\r\n");
      out.write("\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/view/loginstaff.jsp\">スタッフはこちら</a>\r\n");
      out.write("\t</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr style=\"text-align:center; height:5; background-color:#A7CE02\">\r\n");
      out.write("<p>&copy; Copyright 2020 All Right Reserved.</p>");
      out.write("</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
